apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"deployment-1","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"name":"app-1"}},"template":{"metadata":{"labels":{"name":"app-1"}},"spec":{"containers":[{"image":"nginx:latest","name":"nginx","ports":[{"containerPort":80}],"resources":{"limits":{"cpu":"300m","memory":"256Mi"},"requests":{"cpu":"200m","memory":"128Mi"}}}],"restartPolicy":"Always"}}}}
  creationTimestamp: "2019-05-08T03:52:22Z"
  generation: 1
  name: deployment-1
  namespace: default
  resourceVersion: "1124766"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/deployment-1
  uid: af81bdf0-7144-11e9-8c55-00155d74ee29
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: app-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: app-1
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2019-05-08T03:52:27Z"
    lastUpdateTime: "2019-05-08T03:52:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-05-08T03:52:22Z"
    lastUpdateTime: "2019-05-08T03:52:27Z"
    message: ReplicaSet "deployment-1-68689bbfdf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
