apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"name":"app-1"},"name":"app","namespace":"default"},"spec":{"containers":[{"image":"nginx:latest","name":"nginx","ports":[{"containerPort":80,"hostPort":80}],"resources":{"limits":{"cpu":"200m","memory":"128Mi"}}},{"image":"php:latest","name":"mysql","resources":{"limits":{"cpu":"200m","memory":"128Mi"}}}]}}
  creationTimestamp: "2019-05-08T04:02:01Z"
  labels:
    name: app-1
  name: app
  namespace: default
  resourceVersion: "1125606"
  selfLink: /api/v1/namespaces/default/pods/app
  uid: 0881bd5f-7146-11e9-8c55-00155d74ee29
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 200m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-k5tjp
      readOnly: true
  - image: example:latest
    imagePullPolicy: Always
    name: example
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 200m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-k5tjp
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: 172.31.2.13
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-k5tjp
    secret:
      defaultMode: 420
      secretName: default-token-k5tjp
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-05-08T04:02:01Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-05-08T04:02:01Z"
    message: 'containers with unready status: [nginx mysql]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-05-08T04:02:01Z"
    message: 'containers with unready status: [nginx mysql]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-05-08T04:02:01Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: php:latest
    imageID: ""
    lastState: {}
    name: php
    ready: false
    restartCount: 0
    state:
      waiting:
        reason: ContainerCreating
  - image: nginx:latest
    imageID: ""
    lastState: {}
    name: nginx
    ready: false
    restartCount: 0
    state:
      waiting:
        reason: ContainerCreating
  hostIP: 172.31.2.13
  phase: Pending
  qosClass: Guaranteed
  startTime: "2019-05-08T04:02:01Z"