apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-05-08T08:29:02Z"
  name: app-svc
  namespace: default
  resourceVersion: "1148633"
  selfLink: /api/v1/namespaces/default/services/app-svc
  uid: 55f58eae-716b-11e9-8c55-00155d74ee29
spec:
  clusterIP: 10.0.0.249
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 38562
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: app-1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
# kubectl expose deployment deployment-1 --name=app-svc --port=80 --target-port=80 --type=NodePort